add submodule, link to submodule and env0.yaml

diff --git a/env0/acme-fitness/custom-flow/env0.yaml b/env0/acme-fitness/custom-flow/env0.yaml
--- a/env0/acme-fitness/custom-flow/env0.yaml
+++ b/env0/acme-fitness/custom-flow/env0.yaml
@@ -6,7 +6,13 @@ deploy:
       after:
         - name: Download Agent yaml
           run: |
-            curl -u $ENV0_API_KEY:$ENV0_API_SECRET https://api.env0.com/agents/$ENV0_AGENT_KEY/values > agent_values.yaml
+            if [[ -z $ENV0_AGENT_KEY || -z $ENV0_API_KEY || -z $ENV0_API_SECRET]]; then
+              echo "ENV0_AGENT_KEY or ENV0_API_KEY or ENV0_API_SECRET is missing"
+              exit 1
+            elif 
+              curl -u $ENV0_API_KEY:$ENV0_API_SECRET https://api.env0.com/agents/$ENV0_AGENT_KEY/values > agent_values.yaml
+              echo "$ENV0_AGENT_KEY agent values: set your helm values file to use agent_values.yaml"
+            fi
         - name: kubectl check
           run: | 
             kubectl get pod
